-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCqwedadtsYE9ec0L
Jz81vxz+bcfDC/Ri79vZkJg/ldugCgYIKoZIzj0DAQehRANCAAScz+bJabHLAYtb
CZP2Qpj6SboLnCZUyHdSwCydIraJmfF7QvE77C8HofKVl2PiLsXTbwlVj4FBq39V
R6q/x6ZZ
-----END PRIVATE KEY-----